apiVersion: v1
kind: Service
metadata:
  name: {{ include "anvil.fullname" . }}
  labels:
    app: {{ include "anvil.fullname" . }}
spec:
  selector:
    app: {{ include "anvil.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: rpc
